version: "3"
blocks:
  # - name: shell
  #   command: |
  #     v=0
  #     while :; do
  #       echo "value: $v"
  #       (( v++ ))
  #       sleep 2.5
  #     done
  # - name: time
  #   zone: ua
  # - name: clicks
  #   fmt: "clicked %d times"
  - name: sway_layout
    format: "%{short} %{flag} "
  # - name: sway_window
  - name: pulseaudio
    sink_format: "%{sink_icon} %{sink_volume}"
    source_format: "%{source_icon} %{source_volume}"
  # - name: plugin
  #   path: "/home/kraftwerk28/projects/go/src/github.com/kraftwerk28/gost/contrib/build/time.so"
