version: "1"
blocks:
  - name: "time"
    zone: "ua"
    # format: "..."
    # on_click: "..."
  - name: "clicks"
    fmt: "%d clicked"
  # - name: "custom"
  #   script: "~/myscript.sh"
  #   interval: 10
  #   clicks:
  #     - buttons: [left, right]
  #       script: |
  #         echo left or right was clicked at "$x, $y"
  # - name: "custom"
  #   script: "~/myscript-continuous.sh"
  #   interval: "persist" # TODO: change
  # - name: "custom"
  #   script: "~/myscript-continuous.sh"
  #   interval: "repeat" # TODO: change
  # - name: "plugin"
  #   file: "https://url/with/plugin.so"
  #   plugin_specific_setting: 42
  # - name: "plugin"
  #   file: "/path/to/local/plugin.so"
