bat_common: &bat_common
  level_icons: [" ", " ", " ", " ", " "]
  state_icons:
    charging: ''

version: "3"

separator_width: 10

blocks:

  # - name: shell
  #   command: |
  #     date
  #     sleep 1
  #   restart_on_exit: true

  # - name: shell
  #   command: ~/.config/waybar/weather.py
  #   interval: 5s

  # - name: pulseaudio
  #   node: sink
  #   format: "{icon} {volume}"
  #   on_click: |
  #     case $BUTTON in
  #       Right)
  #         /home/kraftwerk28/.config/waybar/switch_audio_sink.py
  #         ;;
  #       Left)
  #         pavucontrol
  #         ;;
  #     esac

  # - name: pulseaudio
  #   node: source
  #   format: "{icon} {volume}"

  # - name: networkmanager
  #   format: "{status_icon$}{strength:3*%}"
  #   status_icons:
  #     connected: "直"
  #     disconnected: "睊"
  #     connecting: " "
  #   primary_only: true

  # - name: cpu

  # - name: shell
  #   command: >
  #     awk -f ~/.config/waybar/cputemp.awk <(sensors)
  #   json: true

  # - <<: *bat_common
  #   name: battery
  #   format: " {percentage:3*%}"
  #   upower_device: keyboard_hid_dco2co26o0co73o0b_battery

  - <<: *bat_common
    urgent_level: 25
    name: battery
    format: "{is_charging$}{state_icon}{percentage:3*%}"

  # - name: sway_layout
  #   format: "{flag}"

  # - name: time

  # - name: plugin
  #   path: /home/kraftwerk28/projects/go/src/github.com/kraftwerk28/gost/contrib/build/time.so
  # - name: battery
  #   device: keyboard_hid_dco2co26o0co73o0b_battery
  # - name: plugin
  #   path: "/home/kraftwerk28/projects/go/src/github.com/kraftwerk28/gost/contrib/build/time.so"
